services:
  webapp:
    environment:
      MONGO_URI: mongodb://database:27017

  event-gateway:
    environment:
      MONGO_URI: mongodb://database:27017

  node-red:
    ports:
      - "1880:1880"
    user: root
    volumes:
      - type: volume
        source: node_red_modules
        target: /data/node_modules
        volume: {}

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - easytek-net

  portainer:
    ports:
    - "9443:9443"
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PORTAINER_DATA_PATH}:/data
    networks:
      - easytek-net

volumes:
  mongo-data:
    name: mongo-data
    driver: local
