services:
  webapp:
    ports:
      - "8050:8050"
    environment:
      MONGO_URI: mongodb://database:27017
    volumes:
      - ./logs:/app/logs

  event-gateway:
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://database:27017

  zpp-processor:
    ports:
      - "5002:5002"
    environment:
      MONGO_URI: mongodb://database:27017
    volumes:
      # Substituir volumes CIFS por diretórios locais para desenvolvimento
      - ./zpp-data/input:/data/input:rw
      - ./zpp-data/output:/data/output:rw
      - ./zpp-data/logs:/data/logs:rw

  node-red:
    ports:
      - "1880:1880"
    user: root
    volumes:
      - type: volume
        source: node_red_modules
        target: /data/node_modules
        volume: {}

  database:
    image: mongo:8.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - easytek-net

  amg-mobile:
    ports:
      - "3001:3000"

  portainer:
    ports:
      - "9443:9443"
    image: portainer/portainer-ce:2.21.4
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PORTAINER_DATA_PATH}:/data
    networks:
      - easytek-net

volumes:
  mongo-data:
    name: mongo-data
    driver: local

  # Sobrescrever volumes CIFS com volumes locais para desenvolvimento
  zpp-input:
    driver: local
  zpp-output:
    driver: local
  zpp-logs:
    driver: local
