

services:
  webapp:
    ports:
      - "8050:8050"
    environment:
      MONGO_URI: mongodb://database:27017

  event-gateway:
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://database:27017

  zpp-processor:
    ports:
      - "5002:5002"
    environment:
      MONGO_URI: mongodb://database:27017

  amg-mobile:
    ports:
      - "3001:3000"

  database:
    image: mongo:8.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - easytek-net

  portainer:
    image: portainer/portainer-ce:2.21.4
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PORTAINER_DATA_PATH}:/data
    networks:
      - easytek-net

volumes:
  mongo-data:
    name: mongo-data
    driver: local
